# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: 'Custom git clone'
  inputs:
    script: |
      echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
      git clone https://github.com/jfrog/project-examples.git
      export JFROG_CLI_LOG_LEVEL=DEBUG
      exit
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ArtSaas'
    cliInstallationRepo: 'jfrog-cli'
    installCustomVersion: true
    cliVersion: '1.53.0'
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'ArtSaas'
    targetResolveRepo: 'nuget'
    solutionPath: 'project-examples/nuget-example/multi-example/multi-example.sln'
- task: CmdLine@2
  displayName: 'find nuget excution file'
  inputs:
    script: |
      echo 'running find command for nuget excutioin file'
      cd /
      find . -name *nuget*
      exit